# Generated by Django 5.2.8 on 2026-01-20 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mno', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('profile', models.ImageField(default='', upload_to='')),
                ('usertype', models.CharField(default='Customer', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cprice', models.IntegerField()),
                ('desc', models.TextField()),
                ('cimage', models.ImageField(default='', upload_to='')),
                ('duration', models.IntegerField()),
                ('tname', models.CharField(max_length=100)),
                ('texp', models.CharField(max_length=20)),
                ('timage', models.ImageField(default='', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
