# Generated by Django 5.2.8 on 2025-12-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cprice', models.IntegerField()),
                ('desc', models.TextField()),
                ('cimage', models.ImageField(default='', upload_to='')),
                ('duration', models.IntegerField()),
                ('tname', models.CharField(max_length=100)),
                ('texp', models.IntegerField()),
            ],
        ),
    ]
