# Generated by Django 5.2.8 on 2025-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='texp',
            field=models.CharField(max_length=20),
        ),
    ]
