# Generated by Django 5.2.8 on 2025-12-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_courses_texp'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='timage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
