# Generated by Django 5.2.8 on 2026-01-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
