# Generated by Django 5.2.8 on 2026-01-16 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 10, 3, 35, 789137, tzinfo=datetime.timezone.utc)),
        ),
    ]
