# Generated by Django 5.2.8 on 2026-01-20 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_wishlist_ttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='ttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
