# Generated by Django 5.2.8 on 2026-02-03 09:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.DateTimeField(default=datetime.datetime(2026, 2, 3, 9, 52, 59, 276916, tzinfo=datetime.timezone.utc))),
                ('tprice', models.IntegerField()),
                ('qty', models.IntegerField(default=1)),
                ('payment', models.BooleanField(default=False)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
