# Generated by Django 5.2.8 on 2026-03-27 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ttime',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 5, 11, 32, 445886, tzinfo=datetime.timezone.utc)),
        ),
    ]
