# Generated by Django 6.0 on 2026-05-05 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_cart_ttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ttime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
